import type { Player } from "./types";

export type LibraryPlayer = Player & { era: string; accent: string };

const player = (data: Omit<LibraryPlayer, "height" | "weight" | "foot" | "secondary"> & Partial<Pick<LibraryPlayer, "height" | "weight" | "foot" | "secondary">>): LibraryPlayer => ({
  height: 180, weight: 75, foot: "右", secondary: data.position, ...data,
});

export const playerLibrary: LibraryPlayer[] = [
  player({ name: "Lionel Messi", nationality: "アルゼンチン", age: 18, position: "RW", secondary: "CAM", number: 10, style: "魔法のチャンスメイカー", overall: 78, potential: 94, height: 170, weight: 67, foot: "左", era: "現役 · 若手再現", source: "current", accent: "#8fd8ff", attributes: { speed: 84, shooting: 78, passing: 82, dribbling: 91, defending: 32, physical: 58 } }),
  player({ name: "Cristiano Ronaldo", nationality: "ポルトガル", age: 18, position: "LW", secondary: "ST", number: 7, style: "ゴールハンター", overall: 76, potential: 93, height: 187, weight: 83, era: "現役 · 若手再現", source: "current", accent: "#d43c44", attributes: { speed: 88, shooting: 77, passing: 69, dribbling: 83, defending: 34, physical: 76 } }),
  player({ name: "Kylian Mbappé", nationality: "フランス", age: 17, position: "ST", secondary: "LW", number: 10, style: "爆発的ラインブレイカー", overall: 74, potential: 94, height: 178, weight: 75, era: "現役 · 若手再現", source: "current", accent: "#4f75e8", attributes: { speed: 94, shooting: 76, passing: 69, dribbling: 84, defending: 31, physical: 68 } }),
  player({ name: "Erling Haaland", nationality: "ノルウェー", age: 17, position: "ST", number: 9, style: "パワーフィニッシャー", overall: 72, potential: 93, height: 195, weight: 94, foot: "左", era: "現役 · 若手再現", source: "current", accent: "#8ad7df", attributes: { speed: 83, shooting: 82, passing: 58, dribbling: 70, defending: 36, physical: 86 } }),
  player({ name: "Lamine Yamal", nationality: "スペイン", age: 16, position: "RW", secondary: "CAM", number: 19, style: "創造的ウインガー", overall: 76, potential: 94, height: 180, weight: 72, foot: "左", era: "現役 · 若手再現", source: "current", accent: "#e5c33c", attributes: { speed: 85, shooting: 72, passing: 80, dribbling: 88, defending: 30, physical: 57 } }),
  player({ name: "Zinedine Zidane", nationality: "フランス", age: 18, position: "CAM", secondary: "CM", number: 10, style: "エレガントな司令塔", overall: 74, potential: 93, height: 185, weight: 80, era: "LEGEND · 1988", source: "legend", accent: "#d9d5c8", attributes: { speed: 72, shooting: 76, passing: 86, dribbling: 88, defending: 52, physical: 74 } }),
  player({ name: "Ronaldo Nazário", nationality: "ブラジル", age: 17, position: "ST", secondary: "CF", number: 9, style: "怪物ストライカー", overall: 78, potential: 95, height: 183, weight: 83, era: "LEGEND · 1993", source: "legend", accent: "#f2d832", attributes: { speed: 93, shooting: 84, passing: 69, dribbling: 90, defending: 28, physical: 81 } }),
  player({ name: "Ronaldinho", nationality: "ブラジル", age: 18, position: "CAM", secondary: "LW", number: 10, style: "トリックスター", overall: 75, potential: 94, height: 182, weight: 80, era: "LEGEND · 1998", source: "legend", accent: "#f0cd2a", attributes: { speed: 82, shooting: 76, passing: 84, dribbling: 92, defending: 32, physical: 70 } }),
  player({ name: "Thierry Henry", nationality: "フランス", age: 18, position: "LW", secondary: "ST", number: 14, style: "万能型フィニッシャー", overall: 73, potential: 93, height: 188, weight: 83, era: "LEGEND · 1995", source: "legend", accent: "#c63d38", attributes: { speed: 91, shooting: 79, passing: 73, dribbling: 82, defending: 38, physical: 76 } }),
  player({ name: "Andrea Pirlo", nationality: "イタリア", age: 18, position: "CM", secondary: "CDM", number: 21, style: "ディープライング・プレイメーカー", overall: 72, potential: 91, height: 177, weight: 68, era: "LEGEND · 1997", source: "legend", accent: "#5a72a8", attributes: { speed: 60, shooting: 72, passing: 89, dribbling: 80, defending: 57, physical: 61 } }),
  player({ name: "Paolo Maldini", nationality: "イタリア", age: 17, position: "LB", secondary: "CB", number: 3, style: "エリートディフェンダー", overall: 74, potential: 94, height: 186, weight: 85, foot: "左", era: "LEGEND · 1985", source: "legend", accent: "#df4747", attributes: { speed: 81, shooting: 48, passing: 72, dribbling: 70, defending: 88, physical: 82 } }),
  player({ name: "Diego Maradona", nationality: "アルゼンチン", age: 16, position: "CAM", secondary: "CF", number: 10, style: "天才ドリブラー", overall: 77, potential: 95, height: 165, weight: 67, foot: "左", era: "ICON · 1976", source: "legend", accent: "#80c9e8", attributes: { speed: 86, shooting: 79, passing: 84, dribbling: 94, defending: 35, physical: 70 } }),
];
