"use client";

import type { Dispatch, SetStateAction } from "react";
import type { GameState, TrainingId } from "@/game/types";
import { announceSelection, completeTraining, trainingOptions } from "@/game/engine";
import { PlayableMatch, type PlayStats } from "./PlayableMatch";
import { LiveMatch } from "./LiveMatch";
import { StadiumCanvas } from "./StadiumCanvas";

export function ConsoleHome({game,onGame,nextOpponent,matchMode,setMatchMode,onFinish,onTab}:{game:GameState;onGame:(g:GameState)=>void;nextOpponent:string;matchMode:"choose"|"play"|"watch";setMatchMode:Dispatch<SetStateAction<"choose"|"play"|"watch">>;onFinish:(mode:"play"|"watch",stats?:PlayStats)=>void;onTab:(tab:string)=>void}) {
  const selected=game.startChance>=47; const status=game.startChance>=47?"STARTING XI":game.startChance>=18?"SUBSTITUTES":"NOT SELECTED"; const nextLabel=game.phase==="training"?"TRAINING DAY":game.phase==="selection"?"TEAM SELECTION":"MATCH DAY";
  if(game.phase==="match"&&matchMode==="play")return <div className="match-stadium-shell"><StadiumCanvas/><PlayableMatch number={game.player.number} opponent={nextOpponent} onFinish={s=>onFinish("play",s)} onBack={()=>setMatchMode("choose")}/></div>;
  if(game.phase==="match"&&matchMode==="watch")return <LiveMatch playerName={game.player.name} opponent={nextOpponent} onFinish={s=>onFinish("watch",s)} onBack={()=>setMatchMode("choose")}/>;
  const competitors=[{name:"Viktor Hansen",ovr:Math.max(72,game.player.overall+4),form:78},{name:game.player.name,ovr:game.player.overall,form:game.form},{name:"Marco Silva",ovr:Math.max(68,game.player.overall-2),form:65},{name:"Noah Williams",ovr:Math.max(64,game.player.overall-5),form:59}].sort((a,b)=>(b.ovr+b.form*.12)-(a.ovr+a.form*.12));
  return <section className={`console-home phase-${game.phase}`}><div className="stadium-glow"/><div className="career-stage"><div className="stage-copy"><span className="eyebrow">{game.date} · WEEK {String(game.week).padStart(2,"0")}</span><strong>{nextLabel}</strong>{game.phase==="match"?<><h1>{game.club}<small>VS</small>{nextOpponent}</h1><p>{game.league}　第{game.week}節 · KICK OFF 19:30</p></>:<><h1>{game.phase==="training"?"次の一歩が、立場を変える。":"監督の決断。"}</h1><p>{game.phase==="training"?"今週のトレーニングを選び、試合への準備を整える。":"直近のフォーム、疲労、戦術適性からメンバーを決定。"}</p></>}</div><div className="stage-player">{game.player.photo?<img src={game.player.photo} alt={game.player.name}/>:<span>{game.player.number}</span>}<b>{game.player.name}</b><small>{game.player.position} · OVR {game.player.overall}</small></div></div>
    {game.phase==="training"&&<div className="next-activity"><div><span>NEXT ACTIVITY</span><h2>トレーニングへ</h2><p>選択した内容が能力、疲労、監督評価へ直接影響します。</p></div><div className="console-training">{(["finishing","passing","tactics","recovery"] as TrainingId[]).map(id=><button key={id} onClick={()=>onGame(completeTraining(game,id))}><b>{trainingOptions[id].name}</b><small>{trainingOptions[id].detail}</small><em>{trainingOptions[id].load>0?`LOAD +${trainingOptions[id].load}`:"RECOVERY"}</em></button>)}</div></div>}
    {game.phase==="selection"&&<div className="selection-stage"><div className="formation-mini"><span>4-3-3</span>{[1,2,3,4,5,6,7,8,9,10,11].map((n,i)=><i key={n} style={{left:`${14+(i%4)*23}%`,top:`${8+Math.floor(i/4)*33}%`}}>{n}</i>)}</div><div><span className="eyebrow">SQUAD ANNOUNCEMENT</span><h2>メンバー発表</h2><p>先発確率 {game.startChance}% · 監督評価 {game.managerTrust}/100</p><button className="console-cta" onClick={()=>onGame(announceSelection(game))}>STARTING XIを確認 <b>→</b></button></div></div>}
    {game.phase==="match"&&<div className="matchday-reveal"><div className={`selection-result ${selected?"selected":"bench"}`}><span>{status}</span><b>{game.player.number}</b><h2>{game.player.name}</h2><p>{selected?"監督は直近のフォームと戦術適性を評価":"試合展開に応じて出場機会があります"}</p></div><div className="match-entry"><span className="eyebrow">CHOOSE MATCH EXPERIENCE</span><h2>試合への入り方</h2><div>{game.careerRole!=="manager"&&<button onClick={()=>setMatchMode("play")}><b>選手を操作</b><small>11対11 · 自分の選手のみ</small></button>}<button onClick={()=>setMatchMode("watch")}><b>リアルタイム観戦</b><small>0分から90分 · HUD / ハイライト</small></button></div></div></div>}
    <div className="career-ribbon"><div><span>監督評価</span><b>{game.managerTrust}</b><i style={{width:`${game.managerTrust}%`}}/></div><div><span>{game.player.position} 序列</span><b>{game.rank}番手</b><small>1番手まで {Math.max(0,competitors[0].ovr-game.player.overall)} OVR</small></div><div><span>今季</span><b>{game.season.goals}G · {game.season.assists}A</b><small>{game.season.appearances}試合 / {game.season.avgRating||"—"} AVG</small></div><button onClick={()=>onTab("選手")}>選手詳細 →</button></div>
    <div className="career-lower"><div className="competition"><div className="console-head"><span>POSITION COMPETITION</span><b>{game.player.position}</b></div>{competitors.map((p,i)=><div className={p.name===game.player.name?"you":""} key={p.name}><span>{i+1}</span><b>{p.name}<small>FORM {p.form}</small></b><strong>{p.ovr}</strong></div>)}</div><div className="manager-model"><div className="console-head"><span>MANAGER DECISION MODEL</span><b>{game.startChance}%</b></div>{[["直近5試合",Math.round(game.form)],["トレーニング",game.sharpness],["戦術適性",Math.round((game.managerTrust+game.player.attributes.passing)/2)],["コンディション",100-game.fatigue]].map(([n,v])=><div key={String(n)}><span>{n}</span><i><b style={{width:`${v}%`}}/></i><strong>{v}</strong></div>)}</div><div className="world-feed"><div className="console-head"><span>WORLD FEED</span><button onClick={()=>onTab("ニュース")}>ALL →</button></div>{game.news.slice(0,4).map(n=><div key={n.id}><span>{n.tag}</span><p>{n.text}</p></div>)}</div></div>
  </section>;
}
