"use client";

import { useEffect, useRef, useState } from "react";
import type { PlayStats } from "./PlayableMatch";
import { chooseAttackPlan, chooseDefensePlan, decisionReason } from "@/game/cpuAI";

const eventPool = [
  ["ATTACK","左サイドから素早く前進"],["PASS","中盤でテンポよくパス交換"],["DUEL","セカンドボールを巡る激しい競り合い"],["FOUL","中盤でファウル。プレー再開"],["SHOT","ペナルティエリア外からシュート"],["SAVE","GKが鋭い反応でセーブ"],["PRESS","高い位置から連動したプレス"],["CORNER","クロスがDFに当たりコーナーキック"],
];

export function LiveMatch({ playerName, opponent, onFinish, onBack }:{ playerName:string; opponent:string; onFinish:(stats:PlayStats)=>void; onBack:()=>void }) {
  const [minute,setMinute]=useState(0); const [running,setRunning]=useState(false); const [score,setScore]=useState<[number,number]>([0,0]); const [possession,setPossession]=useState(51); const [rating,setRating]=useState(6); const [stamina,setStamina]=useState(100); const [events,setEvents]=useState<{min:number;tag:string;text:string}[]>([]); const [stats,setStats]=useState<PlayStats>({goals:0,shots:0,turnovers:0,passes:0,tackles:0}); const clock=useRef(0);
  useEffect(()=>{if(!running)return;const timer=setInterval(()=>{clock.current+=1;const min=Math.min(90,clock.current*2);setMinute(min);setStamina(v=>Math.max(23,v-1.35));setPossession(v=>Math.max(38,Math.min(63,v+(Math.random()-.5)*5)));const ctx={minute:min,scoreDiff:0,stamina:60,possession:51,home:true,style:"possession" as const};const attack=chooseAttackPlan(ctx),defense=chooseDefensePlan(ctx);if(clock.current%2===0){const item=eventPool[Math.floor(Math.random()*eventPool.length)];let tag=item[0],text=`${attack}: ${item[1]}`;if(tag==="SHOT"){setStats(s=>({...s,shots:s.shots+1}));if(Math.random()<.22){tag="GOAL";text=`${playerName}がゴール！${attack}から冷静にネットを揺らした`;setScore(s=>[s[0]+1,s[1]]);setStats(s=>({...s,goals:s.goals+1}));setRating(r=>Math.min(10,r+1.1))}}if(tag==="PASS")setStats(s=>({...s,passes:s.passes+4}));if(tag==="DUEL"&&Math.random()<.5)setStats(s=>({...s,tackles:s.tackles+1}));setEvents(e=>[{min,tag,text},...e].slice(0,7));if(process.env.NODE_ENV!=="production")console.debug("[CPU AI]",decisionReason(attack,defense,ctx))}if(clock.current%13===0&&Math.random()<.35){setScore(s=>[s[0],s[1]+1]);setEvents(e=>[{min,tag:"GOAL",text:`${opponent}が${defense}を崩して得点`},...e].slice(0,7))}if(clock.current>=45){setRunning(false);setMinute(90)}},1000);return()=>clearInterval(timer)},[running,playerName,opponent]);
  return <div className="live-match"><div className="broadcast-score"><div>AFC HARBOR<b>{score[0]}</b></div><strong>{minute}<small>MIN</small></strong><div><b>{score[1]}</b>{opponent}</div></div><div className="broadcast-body"><div className="broadcast-pitch"><div className="scan-line"/><span className="ball-track" style={{left:`${25+minute*.55}%`,top:`${35+Math.sin(minute)*18}%`}}>●</span>{[1,2,3,4,5,6,7,8,9,10,11].map((n,i)=><i className="blue" key={`b${n}`} style={{left:`${10+(i%4)*12}%`,top:`${14+Math.floor(i/4)*32}%`}}>{n}</i>)}{[1,2,3,4,5,6,7,8,9,10,11].map((n,i)=><i className="red" key={`r${n}`} style={{left:`${55+(i%4)*11}%`,top:`${14+Math.floor(i/4)*32}%`}}>{n}</i>)}</div><div className="commentary"><span className="eyebrow">LIVE COMMENTARY</span>{events.map((e,i)=><div className={e.tag==="GOAL"?"goal-event":""} key={`${e.min}-${i}`}><b>{e.min}′</b><span>{e.tag}</span><p>{e.text}</p></div>)}{!events.length&&<p className="awaiting">キックオフを待っています</p>}</div></div><div className="player-hud"><div><span>PLAYER RATING</span><b>{rating.toFixed(1)}</b></div><div><span>STAMINA</span><b>{Math.round(stamina)}%</b></div><div><span>POS</span><b>ST</b></div><div><span>G / A</span><b>{stats.goals} / 0</b></div><div><span>SHOTS</span><b>{stats.shots}</b></div><div><span>PASS</span><b>{Math.min(96,78+stats.passes)}%</b></div><div className="possession-hud"><span>POSSESSION</span><b>{Math.round(possession)} — {100-Math.round(possession)}</b></div></div><div className="broadcast-actions">{minute===0&&<button className="primary" onClick={()=>setRunning(true)}>試合を開始 →</button>}{minute===90&&<button className="primary" onClick={()=>onFinish(stats)}>試合採点へ →</button>}<button className="text-button" onClick={onBack}>モード選択へ戻る</button></div></div>;
}
