"use client";

import { useEffect, useRef, useState } from "react";

export type PlayStats = { goals: number; shots: number; turnovers: number; passes: number; tackles: number };
type Point = { x: number; y: number };
type Owner = "human" | `ally${number}` | `cpu${number}` | null;
type Ball = Point & { vx: number; vy: number; owner: Owner; target: Owner };
type MatchState = { human: Point; allies: Point[]; cpus: Point[]; ball: Ball; score: [number, number]; stamina: number; stats: PlayStats; subs:[number,number] };

const clamp = (v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const dist = (a:Point,b:Point)=>Math.hypot(a.x-b.x,a.y-b.y);
const ALLY_HOME:Point[]=[{x:18,y:18},{x:17,y:39},{x:17,y:63},{x:18,y:84},{x:36,y:28},{x:34,y:54},{x:37,y:77},{x:56,y:24},{x:58,y:72}];
const CPU_HOME:Point[]=[{x:82,y:17},{x:83,y:38},{x:83,y:62},{x:82,y:84},{x:65,y:24},{x:67,y:50},{x:65,y:77},{x:47,y:20},{x:45,y:50},{x:47,y:80}];
const initial = ():MatchState => ({ human:{x:55,y:50}, allies:ALLY_HOME.map(p=>({...p})), cpus:CPU_HOME.map(p=>({...p})), ball:{x:57,y:50,vx:0,vy:0,owner:"human",target:null}, score:[0,0], stamina:100, stats:{goals:0,shots:0,turnovers:0,passes:0,tackles:0},subs:[0,0] });

export function PlayableMatch({ number, opponent, onFinish, onBack }:{ number:number; opponent:string; onFinish:(stats:PlayStats)=>void; onBack:()=>void }) {
  const [match,setMatch]=useState<MatchState>(initial); const [time,setTime]=useState(75); const [running,setRunning]=useState(false); const [message,setMessage]=useState("5対5 MATCH · キックオフ準備完了");
  const keys=useRef<Record<string,boolean>>({}); const ref=useRef(match); const lastDir=useRef({x:1,y:0}); const tackleLock=useRef(0); const aiClock=useRef(0); const goalLock=useRef(false);
  useEffect(()=>{ref.current=match},[match]);
  const reset=(forCpu=false)=>setMatch(m=>({...m,human:{x:55,y:50},allies:ALLY_HOME.map(p=>({...p})),cpus:CPU_HOME.map(p=>({...p})),ball:{x:forCpu?52:57,y:50,vx:0,vy:0,owner:forCpu?"cpu9":"human",target:null}}));
  const kick=(target:Point,power:number,targetOwner:Owner=null)=>setMatch(m=>{if(m.ball.owner!=="human")return m;const dx=target.x-m.ball.x,dy=target.y-m.ball.y,d=Math.hypot(dx,dy)||1;return {...m,ball:{...m.ball,owner:null,target:targetOwner,vx:dx/d*power,vy:dy/d*power}}});
  const shoot=()=>{const m=ref.current;if(!running||m.ball.owner!=="human")return;setMatch(s=>({...s,stats:{...s.stats,shots:s.stats.shots+1}}));kick({x:101,y:clamp(50+lastDir.current.y*22,34,66)},3.35);setMessage("シュート！");};
  const pass=()=>{const m=ref.current;if(!running||m.ball.owner!=="human")return;const options=m.allies.map((p,i)=>({p,i,score:p.x-m.human.x-Math.abs(p.y-m.human.y)*.18})).sort((a,b)=>b.score-a.score);const t=options[0];setMatch(s=>({...s,stats:{...s.stats,passes:s.stats.passes+1}}));kick(t.p,2.25,`ally${t.i}`);setMessage("味方へパス");};
  const tackle=()=>{if(!running||tackleLock.current)return;tackleLock.current=18;setMatch(m=>{const carrier=typeof m.ball.owner==="string"&&m.ball.owner.startsWith("cpu")?m.cpus[+m.ball.owner.slice(3)]:null;if(carrier&&dist(m.human,carrier)<8){setMessage("タックル成功！");return {...m,ball:{...m.ball,owner:"human",target:null},stats:{...m.stats,tackles:m.stats.tackles+1}}}return m});};
  const control=(k:string,v:boolean)=>{keys.current[k]=v};

  useEffect(()=>{const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(["arrowup","arrowdown","arrowleft","arrowright","w","a","s","d"," ","e","shift"].includes(k))e.preventDefault();keys.current[k]=true;if(k===" ")shoot();if(k==="e")tackle();if(k==="q")pass()};const up=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=false};window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up)}});
  useEffect(()=>{if(!running)return;const loop=window.setInterval(()=>{tackleLock.current=Math.max(0,tackleLock.current-1);aiClock.current++;setMatch(m=>{
    const k=keys.current,sprint=!!k.shift&&m.stamina>1;let dx=(k.arrowright||k.d?1:0)-(k.arrowleft||k.a?1:0),dy=(k.arrowdown||k.s?1:0)-(k.arrowup||k.w?1:0);if(dx||dy){const q=Math.hypot(dx,dy);dx/=q;dy/=q;lastDir.current={x:dx,y:dy}}const speed=sprint?1.65:1.12;const human={x:clamp(m.human.x+dx*speed,3,97),y:clamp(m.human.y+dy*speed*1.18,4,96)};let stamina=clamp(m.stamina+(sprint&& (dx||dy)?-.72:.22),0,100);
    const ownerPoint=(owner:Owner):Point|null=>owner==="human"?human:typeof owner==="string"&&owner.startsWith("ally")?m.allies[+owner.slice(4)]:typeof owner==="string"&&owner.startsWith("cpu")?m.cpus[+owner.slice(3)]:null;
    let ball={...m.ball};const carrier=ownerPoint(ball.owner);if(carrier){const toward=ball.owner&&ball.owner.startsWith("cpu")?-1:1;ball.x=carrier.x+toward*2.5;ball.y=carrier.y}else{ball.x+=ball.vx;ball.y+=ball.vy;ball.vx*=.96;ball.vy*=.96;if(ball.y<3||ball.y>97)ball.vy*=-.7;const target=ownerPoint(ball.target);if(target&&dist(ball,target)<5){ball.owner=ball.target;ball.target=null;ball.vx=0;ball.vy=0}}
    let allies=m.allies.map((a,i)=>{const home=ALLY_HOME[i];if(ball.owner===`ally${i}`){const near=m.cpus.some(c=>dist(c,a)<7);if((a.x>80||near)&&aiClock.current%8===0){const tx=101,ty=clamp(50+(Math.random()-.5)*28,35,65),d=Math.hypot(tx-a.x,ty-a.y);ball={...ball,owner:null,target:null,vx:(tx-a.x)/d*2.8,vy:(ty-a.y)/d*2.8};setMessage("味方がシュート")}return{x:clamp(a.x+.62,4,96),y:a.y}}const target=ball.owner&&String(ball.owner).startsWith("cpu")?(i<4?ball:home):home;const d=dist(a,target);return{x:clamp(a.x+(target.x-a.x)/(d||1)*.32,4,96),y:clamp(a.y+(target.y-a.y)/(d||1)*.32,4,96)}});
    let cpus=m.cpus.map((c,i)=>{if(ball.owner===`cpu${i}`){const d=Math.hypot(2-c.x,50-c.y);if(c.x<18&&aiClock.current%7===0){ball={...ball,owner:null,target:null,vx:(2-c.x)/d*3,vy:(50-c.y)/d*3};setMessage("相手のシュート！")}return{x:clamp(c.x-.58,4,96),y:c.y}}const home=CPU_HOME[i];const target=(ball.owner&&String(ball.owner).startsWith("ally"))||ball.owner==="human"?(i<4?human:home):home;const d=dist(c,target);return{x:clamp(c.x+(target.x-c.x)/(d||1)*.35,4,96),y:clamp(c.y+(target.y-c.y)/(d||1)*.35,4,96)}});
    if(ball.owner==="human"){const hit=cpus.findIndex(c=>dist(c,human)<4.2);if(hit>=0&&tackleLock.current===0){ball.owner=`cpu${hit}`;ball.target=null;tackleLock.current=16;setMessage("相手に奪われた");m={...m,stats:{...m.stats,turnovers:m.stats.turnovers+1}}}}
    if(!ball.owner&&Math.hypot(ball.vx,ball.vy)<.65){const people:[Owner,Point][]=[["human",human],...allies.map((p,i)=>[`ally${i}` as Owner,p] as [Owner,Point]),...cpus.map((p,i)=>[`cpu${i}` as Owner,p] as [Owner,Point])];const near=people.sort((a,b)=>dist(a[1],ball)-dist(b[1],ball))[0];if(near&&dist(near[1],ball)<4.5){ball.owner=near[0];ball.target=null}}
    let subs=m.subs;if(aiClock.current===700&&subs[0]===0){subs=[1,subs[1]];setMessage("AFCハーバー：1人目の交代")}if(aiClock.current===940&&subs[1]===0){subs=[subs[0],1];setMessage(`${opponent}：1人目の交代`)}if(!goalLock.current&&ball.x>98&&ball.y>33&&ball.y<67){goalLock.current=true;setMessage("GOAL! チームが得点");setTimeout(()=>{goalLock.current=false;reset(false)},250);return{...m,human,allies,cpus,ball,stamina,subs,score:[m.score[0]+1,m.score[1]],stats:{...m.stats,goals:m.stats.goals+1}}}if(!goalLock.current&&ball.x<2&&ball.y>33&&ball.y<67){goalLock.current=true;setMessage("失点… 切り替えよう");setTimeout(()=>{goalLock.current=false;reset(false)},250);return{...m,human,allies,cpus,ball,stamina,subs,score:[m.score[0],m.score[1]+1]}}if(ball.x>104||ball.x<-4){setTimeout(()=>reset(ball.x>104),50)}return{...m,human,allies,cpus,ball,stamina,subs}
  })},50);const clock=window.setInterval(()=>setTime(t=>{if(t<=1){setRunning(false);setMessage("FULL TIME");return 0}return t-1}),1000);return()=>{clearInterval(loop);clearInterval(clock)}},[running]);

  const pos=(p:Point)=>({left:`${p.x}%`,top:`${p.y}%`});
  return <div className="playable-game three-match"><div className="game-hud"><div><span>AFC</span><b>{match.score[0]}</b></div><strong>{time}<small>SEC</small></strong><div><b>{match.score[1]}</b><span>{opponent.slice(0,3)}</span></div></div><div className="game-message"><b>3D MATCH · 11v11</b>{message}</div><div className="stamina-bar"><span style={{width:`${match.stamina}%`}}/><b>STAMINA {Math.round(match.stamina)}</b></div>
    <div className="three-stage" tabIndex={0}><div className="play-pitch three-pitch"><div className="center-line"/><div className="center-circle"/><div className="penalty-area left"/><div className="penalty-area right"/><div className="goal-net left-goal"/><div className="goal-net"/><span className="keeper ally-keeper" style={{left:"7%",top:"48%"}}>1</span><span className="keeper" style={{left:"93%",top:"48%"}}>1</span>{match.allies.map((p,i)=><span className="ally-player" key={i} style={pos(p)}>{[2,3,4,5,6,8,11,7,9][i]}</span>)}{match.cpus.map((p,i)=><span className="cpu-player" key={i} style={pos(p)}>{[2,3,4,5,6,7,8,9,10,11][i]}</span>)}<span className="human-player" style={pos(match.human)}>{number}</span><span className="game-ball" style={pos(match.ball)}>●</span>{!running&&time===75&&<div className="kickoff-overlay"><b>PLAYER CAREER · 11v11</b><p>22人が連動するフルピッチ。味方と連携し、守備にも戻ろう</p><button onClick={()=>{setRunning(true);setMessage("KICK OFF")}}>キックオフ</button><small>移動 WASD　パス Q　シュート SPACE　タックル E　ダッシュ SHIFT</small></div>}{!running&&time===0&&<div className="kickoff-overlay finished"><b>FULL TIME　{match.score[0]} - {match.score[1]}</b><p>{match.stats.goals}ゴール · {match.stats.shots}シュート · {match.stats.passes}パス · {match.stats.tackles}タックル</p><button onClick={()=>onFinish(match.stats)}>試合結果と採点へ</button></div>}</div><div className="bench-strip home-bench"><b>AFC SUBS</b>{[12,14,15,17,18,20,23].map((n,i)=><span className={i<match.subs[0]?"used":""} key={n}>{n}</span>)}</div><div className="bench-strip away-bench"><b>AWAY SUBS</b>{[12,13,14,16,18,21,22].map((n,i)=><span className={i<match.subs[1]?"used":""} key={n}>{n}</span>)}</div></div>
    <div className="mobile-controls"><div className="dpad">{[["arrowup","▲"],["arrowleft","◀"],["arrowdown","▼"],["arrowright","▶"]].map(([k,l])=><button key={k} onPointerDown={()=>control(k,true)} onPointerUp={()=>control(k,false)} onPointerLeave={()=>control(k,false)}>{l}</button>)}</div><div className="action-buttons"><button onPointerDown={tackle}>TACKLE</button><button onPointerDown={pass}>PASS</button><button className="shoot-button" onPointerDown={shoot}>SHOOT</button></div></div><div className="game-footer"><span>PASS {match.stats.passes}</span><span>SHOT {match.stats.shots}</span><span>TACKLE {match.stats.tackles}</span><span>LOST {match.stats.turnovers}</span><button onClick={onBack}>モード選択へ戻る</button></div>
  </div>;
}
